"""
Unreal Ping Pong
game_globals.py
Created by Justin Leonard
"""

#initialize
import pygame
pygame.init()

#assets external
ALL_MAIN_ALL = 0
ALL_MAIN_GAME = 1
ALL_MAIN_CONTROL = 2
ALL_MAIN_LOC = 3

ALL_ENTITY_BALL_SMALL = 0
ALL_ENTITY_BALL_MEDIUM = 1
ALL_ENTITY_BALL_LARGE = 2
ALL_ENTITY_PLAYER1 = 3
ALL_ENTITY_PLAYER2 = 4
ALL_ENTITY_CLOCK = 5

ALL_UI_INTRO = 0
ALL_UI_NUM = 1
ALL_UI_SCORE = 2
ALL_MAIN_UI = 3
ALL_MAIN_UI_COMMON = 4
ALL_MAIN_UI_PLAY = 5
ALL_MAIN_UI_OPTIONS = 6
ALL_MAIN_UI_PAUSE = 7
ALL_MAIN_UI_BACKGROUND = 8

ALL_SOUND_START = 0
ALL_SOUND_BUTTON = 1
ALL_SOUND_BUTTON_STOP = 2
ALL_SOUND_WIN = 3
ALL_SOUND_END = 4
ALL_SOUND_FINAL = 5
ALL_SOUND_MUSIC = 6
ALL_SOUND_MAINMENU = 7
ALL_SOUND_MAINMENU_OTHER = 8

#assets internal

#main all
MAIN_SIZE_SCREEN = 0
MAIN_SIZE_BALL = 1
MAIN_SPEED_BALL = 2
MAIN_MAX_ROUNDS = 3
MAIN_SOUND_EFFECTS = 4
MAIN_SOUND_MUSIC = 5
MAIN_MENU_CONTROL = 6
MAIN_MENU_PLAY = 7
MAIN_MENU_OPTIONS = 8
MAIN_MENU_PAUSE = 9

#main game
GAME_TIME = 0
GAME_TIME_FINAL = 1
GAME_SECOND = 2
GAME_ROUND = 3
GAME_SPEED = 4
GAME_SPEED_PLAYER = 5
GAME_SPEED_FINAL = 6
GAME_SPEED_FINAL_RESET = 7
GAME_LST = 8
GAME_LST_ROUND = 9

#main control
CONTROL_LOOP = 0
CONTROL_MAIN = 1
CONTROL_MAIN_SCORE = 2
CONTROL_MAIN_WIN = 3
CONTROL_MAIN_WINNER = 4
CONTROL_INITIAL = 5
CONTROL_PLAYER1_UP = 6
CONTROL_PLAYER1_DOWN = 7
CONTROL_PLAYER1_TOP = 8
CONTROL_PLAYER1_BOTTOM = 9
CONTROL_PLAYER2_UP = 10
CONTROL_PLAYER2_DOWN = 11
CONTROL_PLAYER2_TOP = 12
CONTROL_PLAYER2_BOTTOM = 13
CONTROL_PLAYER1_SCORE = 14
CONTROL_PLAYER2_SCORE = 15
CONTROL_BALL = 16
CONTROL_DIRECTION = 17
CONTROL_X = 18
CONTROL_Y = 19

#main locations
LOC_PLAYER1_X = 0
LOC_PLAYER1_Y = 1
LOC_PLAYER2_X = 2
LOC_PLAYER2_Y = 3
LOC_BALL_X = 4
LOC_BALL_Y = 5

#main ui
MAINMENU_UI_LOGO_SMALL = 0
MAINMENU_UI_LOGO_MEDIUM = 1
MAINMENU_UI_LOGO_LARGE = 2
MAINMENU_UI_PLAY = 3
MAINMENU_UI_OPTIONS = 4
MAINMENU_UI_QUIT = 5

#main common
COMMON_UI_BACK = 0
COMMON_UI_SMALL = 1
COMMON_UI_MEDIUM = 2
COMMON_UI_LARGE = 3
COMMON_UI_SLOW = 4
COMMON_UI_FAST = 5
COMMON_UI_ON = 6
COMMON_UI_OFF = 7
COMMON_UI_YES = 8
COMMON_UI_NO = 9
COMMON_UI_LEFT = 10
COMMON_UI_RIGHT = 11

#main play menu
PLAY_BALLSIZE = 0
PLAY_BALLSPEED = 1
PLAY_MAXROUNDS = 2
PLAY_START = 3

#main options menu
OPTIONS_EFFECTS = 0
OPTIONS_MUSIC = 1
OPTIONS_SCREENSIZE = 2

#main pause menu
PAUSE_TITLE = 0
PAUSE_CONTINUE = 1
PAUSE_QUIT = 2

#ui intro
UI_INTRO_GO = 0
UI_INTRO_1 = 1
UI_INTRO_2 = 2
UI_INTRO_3 = 3

#ui number
UI_NUM_0 = 0
UI_NUM_1 = 1
UI_NUM_2 = 2
UI_NUM_3 = 3
UI_NUM_4 = 4
UI_NUM_5 = 5
UI_NUM_6 = 6
UI_NUM_7 = 7
UI_NUM_8 = 8
UI_NUM_9 = 9
UI_NUM_10 = 10

UI_NUMLARGE_0 = 11
UI_NUMLARGE_1 = 12
UI_NUMLARGE_2 = 13
UI_NUMLARGE_3 = 14
UI_NUMLARGE_4 = 15
UI_NUMLARGE_5 = 16
UI_NUMLARGE_6 = 17
UI_NUMLARGE_7 = 18
UI_NUMLARGE_8 = 19
UI_NUMLARGE_9 = 20
UI_NUMLARGE_10 = 21

#ui score
UI_SCORE_DISPLAY = 0
UI_PLAYER1_SCORE = 1
UI_PLAYER1_WIN = 2
UI_PLAYER2_SCORE = 3
UI_PLAYER2_WIN = 4

#main ui background
MAINMENU_UIBG_SCREEN = 0
MAINMENU_UIBG_BACK_SMALL = 1
MAINMENU_UIBG_BACK_MEDIUM = 2
MAINMENU_UIBG_BACK_LARGE = 3
MAINMENU_UIBG_IMAGE_SMALL = 4
MAINMENU_UIBG_IMAGE_MEDIUM = 5
MAINMENU_UIBG_IMAGE_LARGE = 6
BACKGROUND_GAME_SMALL = 7
BACKGROUND_GAME_MEDIUM = 8
BACKGROUND_GAME_LARGE = 9
BACKGROUND_RESET_SMALL = 10
BACKGROUND_RESET_MEDIUM = 11
BACKGROUND_RESET_LARGE = 12
BACKGROUND_BORDER_BLUE_SMALL = 13
BACKGROUND_BORDER_BLUE_MEDIUM = 14
BACKGROUND_BORDER_BLUE_LARGE = 15
BACKGROUND_BORDER_RED_SMALL = 16
BACKGROUND_BORDER_RED_MEDIUM = 17
BACKGROUND_BORDER_RED_LARGE = 18
BACKGROUND_FINAL_SMALL = 19
BACKGROUND_FINAL_MEDIUM = 20
BACKGROUND_FINAL_LARGE = 21

#game rounds
ROUND_NUM_2 = 0
ROUND_NUM_4 = 1
ROUND_NUM_6 = 2
ROUND_NUM_8 = 3
ROUND_NUM_10 = 4
ROUND_NUM_12 = 5
ROUND_NUM_14 = 6
ROUND_NUM_16 = 7
ROUND_NUM_18 = 8

#screen
screen_info = pygame.display.Info()

SCREEN_SMALL = 0
SCREEN_MEDIUM = 1
SCREEN_LARGE = 2

SCREEN_SIZE_SMALL_X = 640
SCREEN_SIZE_SMALL_Y = 480
SCREEN_SIZE_MEDIUM_X = 800
SCREEN_SIZE_MEDIUM_Y = 600
SCREEN_SIZE_LARGE_X = 1024
SCREEN_SIZE_LARGE_Y = 700
SCREEN_SIZE_FULLSCREEN_X = screen_info.current_w
SCREEN_SIZE_FULLSCREEN_Y = screen_info.current_h

SCREEN_MID_SMALL_X = 320
SCREEN_MID_SMALL_Y = 240
SCREEN_MID_MEDIUM_X = 400
SCREEN_MID_MEDIUM_Y = 300
SCREEN_MID_LARGE_X = 512
SCREEN_MID_LARGE_Y = 380
SCREEN_MID_FULLSCREEN_X = (screen_info.current_w / 2)
SCREEN_MID_FULLSCREEN_Y = (screen_info.current_h / 2)

SCREEN_SIZE_SMALL = (SCREEN_SIZE_SMALL_X,SCREEN_SIZE_SMALL_Y)
SCREEN_SIZE_MEDIUM = (SCREEN_SIZE_MEDIUM_X,SCREEN_SIZE_MEDIUM_Y)
SCREEN_SIZE_LARGE = (SCREEN_SIZE_LARGE_X,SCREEN_SIZE_LARGE_Y)
SCREEN_SIZE_FULLSCREEN = (SCREEN_SIZE_FULLSCREEN_X,SCREEN_SIZE_FULLSCREEN_Y)
